### ISSUE TITLE
Can't discover existing feed

### ISSUE THREAD

**Issue by Stajor** [damog/feedbag#19]
Hi.
I tried get existing feed on the page
```
Feedbag.find 'https://habrahabr.ru/hub/ruby/'
```
but got an error
```
Error occurred with `https://habrahabr.ru/hub/ruby/': 403 Forbidden
```

On the web page source I see the feed tag
```
  <link title="Хабрахабр / Все публикации подряд / Ruby" type="application/rss+xml" rel="alternate" href="https://habrahabr.ru/rss/hub/ruby/all/"/>
```

**Comment by damog** [comment]
Sorry I replied only 3 years later :) This website breaks now:

`Error occurred with `https://habrahabr.ru/hub/ruby/': 503 Service Temporarily Unavailable`

Thoughts?

**Comment by damog** [comment]
No reply.
