### ISSUE TITLE
Feedbag mistakenly tells that html page is feed

### ISSUE THREAD

**Issue by VladYermakov** [damog/feedbag#22]
`Feedbag.feed?('https://aeon.co/culture')` returns `true` while this link is actually html page.  
BTW, https://validator.w3.org/feed/ says that this link looks like a web page rather than feed.

**Comment by VladYermakov** [comment]
Looks like this link is returning html when open it from browser and atom when requesting it from open-uri or curl

**Comment by damog** [comment]
Interesting. That's a very sneaky feature indeed. Any ideas how to get more information from the webmaster?

`➜  /home/damog  curl -s -I https://aeon.co/culture | grep -i ^content-type
content-type: application/atom+xml; charset=utf-8
➜  /home/damog `

I agree this is not a bug/issue on Feedbag. Thanks for reporting.
