### ISSUE TITLE
Ruby 2.7 warnings

### ISSUE THREAD

**Issue by hwo411** [damog/feedbag#24]
After migrating our app to Ruby 2.7 we see the following warning:
`/usr/local/bundle/ruby/2.7.0/gems/feedbag-0.10/lib/feedbag.rb:100: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open`

Could you change the code to hide the warnings?

**Comment by damog** [comment]
MRs welcome!
